config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts
  resources :categories
  resources :comments, only: [:create, :new]

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commentable

  validates :title, length: { maximum: 255 }, presence: true
  validates :link, presence: true, if: :link?
  validates :link, length: { maximum: 2000 }
  validates :body, presence: true, if: :text?
  validates :category_id, presence: true
  enum post_type: [:link, :text]

  belongs_to :category
  belongs_to :user
  default_scope { order(:created_at => :desc) }
  scope :added_today, -> { where('created_at > ?', Time.now.beginning_of_day) }
  scope :with_categories, -> { includes(:category) }
  scope :with_users, -> {includes(:user)}

  self.per_page = 10
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.with_categories.with_users.includes(:comment_threads).page(params[:page])
    # scopes can be chained as well
    # @posts = Post.with_categories.added_today
    render :index
  end

  def show
    @comment = Comment.build_from(@post, current_user.id, '')
  end

  def new
    @post = Post.new
    @post.post_type = params[:post_type] if params[:post_type].present?
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to new_post_path, flash: { notice: 'Post successfully added.' }
    else
      flash.now[:error] = @post.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, flash: { notice: 'Post successfully updated.' }
    else
      flash.now[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, flash: { notice: 'Your post has been removed.' }
    else
      redirect_to posts_path, flash: { notice: 'We were unable to remove that post.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :link, :body, :post_type, :category_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/views/posts/_actions.html.erb
<% if user_signed_in? -%>
  <ul class="actions">
    <li><%= link_to 'edit', edit_post_path(post) %></li>
    <li>
      <%= link_to 'delete', post_path(post), method: :delete, data: { confirm: 'Are you sure? This cannot be undone.' } %>
    </li>
    <li><%= link_to "#{post.comment_threads.length} #{'comment'.pluralize(post.comment_threads.length)}", post_path(post, anchor: 'comments') %></li>
  </ul>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
  <% if f.object.link? %>
    <%= f.label :link %>
    <%= f.text_field :link %>
  <% else %>
    <%= f.label :body %>
    <%= f.text_area :body %>
  <% end %>
  </fieldset>

  <fieldset>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: 'Select a Category' %>
  </fieldset>

  <%= f.hidden_field :post_type %>

  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/posts/_heading.html.erb
<%= post_title_link(post) %>
<div class="tagline" title="<%= post.created_at %>">
  submitted <%= time_ago_in_words post.created_at %> ago
  to <%= link_to post.category.name, category_path(post.category) %>
  by <%= post.user.username %>
</div>

app/views/posts/_list.html.erb
<ul class="posts">
  <% posts.each do |post| %>
    <li>
      <%= render('posts/heading', {post: post}) %>
      <%= render('posts/actions', {post: post}) %>
    </li>
  <% end %>
</ul>
<%= will_paginate(posts) %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render('form') %>

app/views/posts/index.html.erb
<%= render('list', {posts: @posts}) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
  <% if f.object.link? %>
    <%= f.label :link %>
    <%= f.text_field :link %>
  <% else %>
    <%= f.label :body %>
    <%= f.text_area :body %>
  <% end %>
  </fieldset>

  <%= f.hidden_field :post_type %>

  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/posts/show.html.erb
<article class="post">
  <%= render('heading', {post: @post}) %>

  <% if @post.text? %>
    <section class="body"><%= @post.body %></section>
  <% end %>

  <%= render('actions', {post: @post}) %>

  <%= render('comments/form', {comment: @comment}) %>

  <%= nested_ol @post.comment_threads, id: 'comments' do |comment| %>
    <div class="tagline" title="<%= comment.created_at %>">
      <%= comment.user.username %>
      <%= time_ago_in_words comment.created_at %> ago
    </div>

    <section class="body">
      <%= comment.body %>
    </section>

    <ul class="actions">
      <li><%= link_to 'reply', new_comment_path(parent_id: comment.id, format: 'js'), remote: true, method: :get %></li>
    </ul>

    <div id="reply-form-<%= comment.id %>" style="display: none"></div>
 <% end -%>
</article>