config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts
  resources :categories
  resources :comments, only: [:create, :new]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Elevennit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container wrap">
    <div class="row">
      <div class="col-xs-12">
        <nav id="categories">

          <div class="dropdown">
            <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
             <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
              <% categories.each do |c| -%>
                <li role="presentation"><%= link_to c.name, category_path(c), role: 'menuitem', tabindex: '-1' %></li>
              <% end -%>
            </ul>
          </div>
          <span class="separator">|</span>
          <ul class="category-links">
            <% categories.each_with_index do |c, i| -%>
              <% if i > 0 -%>
                <span class="separator">-</span>
              <% end %>
              <li><%= link_to c.name, category_path(c) %></li>
            <% end %>
          </ul>
        </nav>
        <header>
          <%= link_to("Elevennit", root_path) %>
          <div id="session-actions">
            <% if user_signed_in? -%>
              <%= link_to current_user.username, edit_user_registration_path(current_user) %>
              <span class="separator">|</span>
              <%= link_to 'logout', destroy_user_session_path, method: :delete %>
            <% else -%>
              want to join? <%= link_to 'login', new_user_session_path %>
              or <%= link_to 'register', new_user_registration_path %>
            <% end -%>
          </div>
        </header>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-xs-8">
          <main>
            <% flash.each do |k, v| %>
              <% if v.is_a?(Array) %>
                <%= content_tag :div, class: "alert #{flash_class(k)}" do %>
                  <ul>
                    <% v.each do |msg| %>
                      <%= content_tag :li, msg %>
                    <% end %>
                  </ul>
                <% end %>
              <% else %>
                <%= content_tag :div, v, class: "alert #{flash_class(k)}" %>
              <% end %>
            <% end %>
            <!-- BEGIN main content -->
            <%= yield %>
            <!-- END main content -->
          </main>
        </div>
        <div class="col-xs-4">
          <nav id="sidebar">
            <% if user_signed_in? -%>
              <%= link_to('Submit a New Link', new_post_path) %>
              <%= link_to('Submit a New Post', new_post_path(post_type: :text)) %>
              <%= link_to('Create a New Category', new_category_path) %>
              <!-- yield any content provided by a call to the sidebar helper -->
              <div><%= yield :sidebar %></div>
            <% end %>
          </nav>
        </div>
      </div>
    </div>
    <div class="push"></div>
  </div>

  <footer>
    Use of this site constitutes acceptance of the <a 47 href="http://dresdenfiles.wikia.com/wiki/Unseelie_Accords">Unseelie Accords</a>.
  </footer>
</body>
</html>